#spring:
#  cloud:
#    gateway:
#      mvc:
#        routes:
#          - id: r1
#            uri: http://localhost:8888
#            predicates:
#              - Path=/customers/**
#          - id: r2
#            uri: http://localhost:9999
#            predicates:
#              - Path=/products/**